version: '3'

services:
  demo_mysql:
    container_name: demo_mysql
    image: mysql:8
    restart: always
    hostname: demo_mysql
    networks: {demo_net: {ipv4_address: 172.21.0.2}}
    logging: {driver: "json-file", options: {max-size: "10m", max-file: "10"}}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=demo
#    volumes:
#    - /data/demo/mysql/:/var/lib/mysql

networks:
  demo_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.21.0.0/24
